/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFarmChatRouteImport } from './routes/api/farm-chat'
import { Route as ApiPlantDiagnosisRouteImport } from './routes/api/plant-diagnosis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarmChatRoute = ApiFarmChatRouteImport.update({
  id: '/api/farm-chat',
  path: '/api/farm-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlantDiagnosisRoute = ApiPlantDiagnosisRouteImport.update({
  id: '/api/plant-diagnosis',
  path: '/api/plant-diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/api/plant-diagnosis': typeof ApiPlantDiagnosisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/api/plant-diagnosis': typeof ApiPlantDiagnosisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/api/plant-diagnosis': typeof ApiPlantDiagnosisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/farm-chat' | '/api/plant-diagnosis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/farm-chat' | '/api/plant-diagnosis'
  id: '__root__' | '/' | '/api/farm-chat' | '/api/plant-diagnosis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFarmChatRoute: typeof ApiFarmChatRoute
  ApiPlantDiagnosisRoute: typeof ApiPlantDiagnosisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farm-chat': {
      id: '/api/farm-chat'
      path: '/api/farm-chat'
      fullPath: '/api/farm-chat'
      preLoaderRoute: typeof ApiFarmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plant-diagnosis': {
      id: '/api/plant-diagnosis'
      path: '/api/plant-diagnosis'
      fullPath: '/api/plant-diagnosis'
      preLoaderRoute: typeof ApiPlantDiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFarmChatRoute: ApiFarmChatRoute,
  ApiPlantDiagnosisRoute: ApiPlantDiagnosisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
